services:
  - type: web
    name: fraudshield
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars: []
    build:
      apt:
        - tesseract-ocr
        - tesseract-ocr-eng
        - tesseract-ocr-all
        - libtesseract-dev
